server.port=8080
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/Gayatri_Member_Association?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}

#for local
#spring.datasource.url=jdbc:mysql://localhost:3306/Gayatri_Member_Association
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driverClassName=com.mysql.jdbc.Driver

spring.jpa.properties.hibernate.id.new_generator_mappings=false





#JPA Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


twilio.account_sid=AC427e8ab9becd4c9c0e3ef1e6680a604c
twilio.auth_token=46ebc8296a6ac69f3771f087e9e49d51
twilio.phone_number=+18578772797
twilio.whatsapp.number=whatsapp:+14155238886






